// Resume building blocks per job family. "core" bullets state skills explicitly;
// "adjacent" bullets describe the same experience in different words (what keyword search
// misses); "generic" bullets are vague and should not count as evidence.

export interface Family {
  key: string;
  titles: [string, string, string];
  core: string[];
  adjacent: string[];
  generic: string[];
  skills: string[];
  degrees: string[];
  count: number;
}

export const FAMILIES: Family[] = [
  {
    key: "fullstack",
    count: 10,
    titles: ["Software Engineer", "Full Stack Developer", "Senior Full Stack Engineer"],
    core: [
      "Built customer-facing dashboards in React and TypeScript used by 40k monthly users",
      "Developed REST APIs in Node.js (Express) serving 2M requests/day",
      "Designed PostgreSQL schemas and migrations for the billing domain",
      "Deployed services to AWS (ECS, RDS, S3) and owned them in production on-call",
      "Led a 4-engineer project to rebuild onboarding end to end, from API to UI",
      "Mentored 3 junior engineers through code review and pairing",
      "Worked on a B2B SaaS product sold to mid-market logistics companies",
      "Migrated a monolith to Node.js microservices with a shared MySQL database",
    ],
    adjacent: [
      "Wrote the web client in Next.js with hooks-based components and server rendering",
      "Built server-side services on Express and NestJS, running on the V8 runtime",
      "Modeled relational data and tuned slow queries in Postgres",
      "Shipped features for business customers on a subscription platform",
      "Ran production workloads on Google Cloud Run and Cloud SQL",
    ],
    generic: [
      "Participated in agile ceremonies and sprint planning",
      "Worked closely with product and design",
      "Contributed to various features across the stack",
      "Improved code quality and team processes",
    ],
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS", "Docker", "GraphQL", "Redis"],
    degrees: ["B.Sc. Computer Science, Tel Aviv University", "B.Sc. Software Engineering, Technion", "Full-stack bootcamp, Coding Academy"],
  },
  {
    key: "frontend",
    count: 7,
    titles: ["Frontend Developer", "Frontend Engineer", "Senior Frontend Engineer"],
    core: [
      "Built a React + TypeScript trading interface rendering live order books",
      "Implemented WCAG 2.1 AA accessibility fixes across 60 screens, verified with screen readers",
      "Created and maintained the company component library and design system in Storybook",
      "Improved Largest Contentful Paint from 4.1s to 1.6s through code splitting and image optimization",
      "Wrote end-to-end tests with Playwright and unit tests with Testing Library",
      "Built responsive layouts for mobile web and desktop",
    ],
    adjacent: [
      "Wrote strongly typed UI code with strict compiler settings and generics",
      "Built single-page apps with Vue 3 and Pinia",
      "Made keyboard navigation and focus management work for users of assistive technology",
      "Owned the shared button, form and table primitives used by 5 product teams",
    ],
    generic: ["Translated designs into pixel-perfect UI", "Worked in a fast-paced startup environment", "Fixed bugs reported by customers"],
    skills: ["React", "TypeScript", "CSS", "Next.js", "Playwright", "Storybook", "Vite"],
    degrees: ["B.A. Interactive Design, Shenkar", "B.Sc. Computer Science, Open University", "Frontend bootcamp, ITC"],
  },
  {
    key: "backend",
    count: 7,
    titles: ["Backend Developer", "Backend Engineer", "Senior Backend Engineer"],
    core: [
      "Built payment authorization services in Go handling 1,500 TPS",
      "Developed Python (FastAPI) microservices for merchant onboarding",
      "Designed gRPC APIs consumed by 6 internal teams",
      "Implemented a double-entry ledger for wallet balances and reconciliation",
      "Built event-driven workflows on Kafka for settlement notifications",
      "Led PCI-DSS scope reduction by tokenizing card data",
    ],
    adjacent: [
      "Wrote Django services and Celery workers for invoicing",
      "Integrated card acquirers and handled chargebacks and refunds flows",
      "Published and versioned internal HTTP interfaces with OpenAPI",
      "Processed asynchronous messages with RabbitMQ and SQS",
    ],
    generic: ["Maintained backend systems", "Worked on scalability and reliability", "Collaborated with frontend developers"],
    skills: ["Go", "Python", "PostgreSQL", "Kafka", "gRPC", "Docker", "Kubernetes"],
    degrees: ["B.Sc. Computer Science, Hebrew University", "B.Sc. Mathematics & CS, Ben-Gurion University", "M.Sc. Computer Science, Weizmann Institute"],
  },
  {
    key: "devops",
    count: 6,
    titles: ["DevOps Engineer", "Platform Engineer", "Senior Site Reliability Engineer"],
    core: [
      "Operated 12 production Kubernetes (EKS) clusters running 400 services",
      "Wrote Terraform modules for VPCs, IAM and RDS used across all AWS accounts",
      "Built CI/CD pipelines in GitHub Actions and ArgoCD, cutting deploy time from 40 to 8 minutes",
      "Rolled out Prometheus and Grafana monitoring with SLO-based alerting",
      "Reduced AWS spend by 31% through rightsizing and spot instances",
      "Led incident response as on-call lead and ran blameless postmortems",
    ],
    adjacent: [
      "Managed container orchestration with Helm charts and GitOps",
      "Codified cloud infrastructure with Pulumi and CloudFormation",
      "Automated build and release workflows in Jenkins and GitLab",
      "Set up Datadog dashboards and paging for customer-facing APIs",
    ],
    generic: ["Supported developers with infrastructure requests", "Maintained Linux servers", "Improved system stability"],
    skills: ["Kubernetes", "Terraform", "AWS", "Helm", "ArgoCD", "Prometheus", "Linux"],
    degrees: ["B.Sc. Information Systems, Technion", "Practical Engineering, ORT Braude", "B.Sc. Computer Science, Bar-Ilan University"],
  },
  {
    key: "data_eng",
    count: 6,
    titles: ["BI Developer", "Data Engineer", "Senior Data Engineer"],
    core: [
      "Built batch pipelines in Spark processing 3TB/day into the lakehouse",
      "Orchestrated 200+ Airflow DAGs with SLAs and alerting",
      "Modeled analytics layers in dbt with tests and documentation",
      "Wrote complex SQL (window functions, CTEs) for finance and product reporting",
      "Built streaming ingestion from Kafka into Snowflake",
      "Migrated the warehouse from Redshift to BigQuery",
    ],
    adjacent: [
      "Scheduled data workflows with Dagster and Prefect",
      "Transformed raw events into clean fact and dimension tables",
      "Consumed CDC streams with Kinesis and Flink",
      "Wrote PySpark jobs on Databricks",
    ],
    generic: ["Worked with large amounts of data", "Supported analysts with data requests", "Improved data quality"],
    skills: ["SQL", "Spark", "Airflow", "dbt", "Snowflake", "Kafka", "Python"],
    degrees: ["B.Sc. Industrial Engineering, Tel Aviv University", "B.Sc. Statistics, Hebrew University", "B.Sc. Computer Science, Reichman University"],
  },
  {
    key: "ml",
    count: 5,
    titles: ["Data Scientist", "Machine Learning Engineer", "Senior ML Engineer"],
    core: [
      "Trained and deployed a PyTorch ranking model that lifted CTR by 7%",
      "Built NLP classification models for support ticket routing in production",
      "Shipped a recommendation system serving 5M users with real-time features",
      "Set up MLflow experiment tracking and model monitoring for drift",
      "Fine-tuned and evaluated large language models for summarization",
      "Published a paper at EMNLP on low-resource text classification",
    ],
    adjacent: [
      "Productionized TensorFlow models behind a low-latency inference service",
      "Built a feature store and offline/online parity checks",
      "Developed collaborative filtering for content personalization",
      "Maintained an open-source library for text embeddings (1.2k GitHub stars)",
    ],
    generic: ["Explored data and built proofs of concept", "Presented findings to stakeholders", "Worked on AI initiatives"],
    skills: ["Python", "PyTorch", "TensorFlow", "scikit-learn", "MLflow", "SQL"],
    degrees: ["M.Sc. Computer Science (ML), Technion", "Ph.D. Physics, Weizmann Institute", "M.Sc. Data Science, Tel Aviv University"],
  },
  {
    key: "ios",
    count: 4,
    titles: ["Mobile Developer", "iOS Engineer", "Senior iOS Engineer"],
    core: [
      "Built native iOS features in Swift and SwiftUI for a banking app with 800k installs",
      "Shipped 30+ releases to the App Store and managed TestFlight betas",
      "Implemented offline-first sync with Core Data and background tasks",
      "Automated builds and signing with Fastlane and Xcode Cloud",
    ],
    adjacent: [
      "Developed UIKit screens and custom animations",
      "Built cross-platform screens in React Native",
      "Maintained the iPhone app's release train and App Review submissions",
    ],
    generic: ["Worked on the mobile app", "Fixed crashes", "Collaborated with designers"],
    skills: ["Swift", "SwiftUI", "UIKit", "Core Data", "Fastlane"],
    degrees: ["B.Sc. Computer Science, Ariel University", "B.Sc. Software Engineering, Afeka"],
  },
  {
    key: "qa",
    count: 5,
    titles: ["QA Engineer", "QA Automation Engineer", "Senior QA Automation Engineer"],
    core: [
      "Built an end-to-end test suite in Playwright covering 400 user flows",
      "Wrote API tests with REST Assured and Postman collections",
      "Integrated automated tests into GitHub Actions with parallel sharding",
      "Ran load tests with k6 before major launches",
      "Wrote test automation frameworks in TypeScript and Python",
    ],
    adjacent: [
      "Automated browser regression with Selenium WebDriver and Cypress",
      "Validated backend endpoints and contracts automatically",
      "Made the test stage a required gate in the Jenkins pipeline",
    ],
    generic: ["Performed manual testing and wrote test plans", "Reported bugs in Jira", "Participated in release cycles"],
    skills: ["Playwright", "Cypress", "Selenium", "Postman", "k6", "TypeScript"],
    degrees: ["QA course, John Bryce", "B.A. Economics, Tel Aviv University", "B.Sc. Biology, Hebrew University"],
  },
  {
    key: "security",
    count: 4,
    titles: ["Security Analyst", "Application Security Engineer", "Senior Security Engineer"],
    core: [
      "Led threat modeling and secure code reviews for 20 product teams",
      "Ran external penetration tests and managed the bug bounty program on HackerOne",
      "Secured AWS accounts with SCPs, GuardDuty and least-privilege IAM",
      "Integrated SAST/DAST (Semgrep, ZAP) into CI",
      "Drove SOC 2 Type II and ISO 27001 certification",
      "Holds OSCP certification",
    ],
    adjacent: [
      "Found and triaged vulnerabilities in web applications and APIs",
      "Hardened GCP projects and Kubernetes workloads",
      "Reviewed architecture designs for security risks",
    ],
    generic: ["Monitored security alerts", "Raised security awareness", "Worked with IT on policies"],
    skills: ["Threat modeling", "Burp Suite", "AWS security", "Semgrep", "Python"],
    degrees: ["B.Sc. Computer Science, Tel Aviv University", "Unit 8200 cyber training program"],
  },
  {
    key: "em",
    count: 4,
    titles: ["Tech Lead", "Engineering Manager", "Senior Engineering Manager"],
    core: [
      "Managed a team of 8 software engineers: hiring, 1:1s and performance reviews",
      "Grew the team from 3 to 14 engineers during Series B growth",
      "Delivered a cross-team migration involving 4 teams and 30 services",
      "Previously wrote production Java and Python services for 6 years",
    ],
    adjacent: [
      "Ran weekly one-on-ones and career plans for direct reports",
      "Coordinated delivery across multiple squads with shared roadmaps",
      "Worked at a subscription software company selling to enterprises",
    ],
    generic: ["Responsible for team success", "Drove engineering excellence", "Aligned stakeholders"],
    skills: ["People management", "Java", "Python", "System design", "Hiring"],
    degrees: ["B.Sc. Computer Science, Technion", "MBA, Tel Aviv University"],
  },
  {
    key: "pm",
    count: 6,
    titles: ["Associate Product Manager", "Product Manager", "Senior Product Manager"],
    core: [
      "Owned the roadmap for a B2B SaaS workflow product with $12M ARR",
      "Ran discovery interviews with enterprise customers such as banks and insurers",
      "Defined north-star metrics and built product analytics dashboards in Amplitude",
      "Led pricing and packaging changes that increased ARPA by 18%",
      "Former software engineer (4 years) before moving to product",
    ],
    adjacent: [
      "Prioritized the backlog for a platform sold to large corporate accounts",
      "Met Fortune 500 users to validate problems before building",
      "Tracked activation and retention KPIs and ran experiments",
    ],
    generic: ["Worked with R&D to deliver features", "Wrote PRDs", "Managed stakeholders"],
    skills: ["Product discovery", "Roadmapping", "Amplitude", "SQL", "Jira"],
    degrees: ["B.Sc. Industrial Engineering, Technion", "B.A. Economics & Management, Tel Aviv University", "MBA, INSEAD"],
  },
  {
    key: "design",
    count: 5,
    titles: ["UI/UX Designer", "Product Designer", "Senior Product Designer"],
    core: [
      "Designed end-to-end flows for a web analytics product in Figma, from research to handoff",
      "Ran usability tests and user interviews every sprint",
      "Built and maintained the company design system (tokens, components, docs)",
      "Designed data-heavy dashboards for operations teams",
      "Portfolio: shipped mobile banking redesign used by 1M customers",
    ],
    adjacent: [
      "Prototyped interactions and handed off specs to engineers",
      "Validated concepts with customers through moderated sessions",
      "Created a shared component kit for 4 product squads",
    ],
    generic: ["Created beautiful visual designs", "Collaborated with product managers", "Designed marketing assets"],
    skills: ["Figma", "Prototyping", "User research", "Design systems"],
    degrees: ["B.Des. Visual Communication, Bezalel", "B.Des. Industrial Design, Shenkar"],
  },
  {
    key: "analyst",
    count: 5,
    titles: ["Junior Data Analyst", "Data Analyst", "Senior Data Analyst"],
    core: [
      "Wrote SQL on 2B-row event tables in BigQuery for product analysis",
      "Built executive dashboards in Looker and Tableau",
      "Presented weekly insights to the VP Sales and VP Marketing",
      "Designed and analyzed A/B tests on onboarding flows",
      "Automated analyses with Python (pandas)",
    ],
    adjacent: [
      "Created Power BI reports for finance and operations",
      "Queried the warehouse to answer business questions",
      "Shared findings with leadership in monthly reviews",
    ],
    generic: ["Worked with Excel", "Supported business teams", "Prepared reports"],
    skills: ["SQL", "Looker", "Tableau", "Python", "Excel"],
    degrees: ["B.A. Economics, Hebrew University", "B.Sc. Industrial Engineering, Ben-Gurion University"],
  },
  {
    key: "csm",
    count: 4,
    titles: ["Customer Success Associate", "Customer Success Manager", "Senior Customer Success Manager"],
    core: [
      "Managed a portfolio of 45 B2B SaaS accounts worth $4M ARR",
      "Drove 112% net revenue retention through renewals and expansion",
      "Ran onboarding programs and quarterly business reviews (QBRs)",
      "Managed enterprise accounts including two Fortune 100 customers",
      "Built health scores and playbooks in Gainsight",
    ],
    adjacent: [
      "Owned renewals for subscription customers and upsold add-ons",
      "Led kickoff and implementation for new corporate clients",
    ],
    generic: ["Answered customer questions", "Built strong relationships", "Handled escalations"],
    skills: ["Gainsight", "Salesforce", "Onboarding", "Renewals"],
    degrees: ["B.A. Communications, IDC Herzliya", "B.A. Business Administration, College of Management"],
  },
  {
    key: "ae",
    count: 4,
    titles: ["Sales Development Rep", "Account Executive", "Senior Account Executive"],
    core: [
      "Closed $1.4M in new B2B SaaS ARR in 2024 (128% of quota)",
      "Exceeded quota for 7 consecutive quarters",
      "Ran full-cycle sales from discovery and demo to negotiation and close",
      "Sold to CTOs and engineering leaders",
      "Managed pipeline and forecasting in Salesforce",
    ],
    adjacent: [
      "Brought in new logos for a subscription software platform",
      "Hit 110% of target selling to IT decision makers",
    ],
    generic: ["Built relationships with clients", "Prospected new business", "Attended trade shows"],
    skills: ["Salesforce", "MEDDICC", "Negotiation", "HubSpot"],
    degrees: ["B.A. Business, Reichman University", "B.A. Political Science, Tel Aviv University"],
  },
  {
    key: "marketing",
    count: 4,
    titles: ["Marketing Coordinator", "Growth Marketing Manager", "Head of Growth"],
    core: [
      "Ran paid campaigns on Google Ads, Meta and LinkedIn with a $150k monthly budget",
      "Owned CAC and payback targets for self-serve acquisition",
      "Ran 40+ landing page and funnel experiments per quarter",
      "Built nurture flows in HubSpot marketing automation",
      "Led growth marketing for a B2B SaaS product",
    ],
    adjacent: [
      "Managed performance marketing spend across search and social channels",
      "Tested signup page variants to improve conversion",
    ],
    generic: ["Managed social media accounts", "Wrote blog posts", "Organized events"],
    skills: ["Google Ads", "Meta Ads", "HubSpot", "GA4", "Experimentation"],
    degrees: ["B.A. Marketing, College of Management", "B.A. Psychology, Tel Aviv University"],
  },
  {
    key: "hr",
    count: 3,
    titles: ["HR Generalist", "HR Business Partner", "Senior HRBP"],
    core: [
      "Partnered with R&D and Sales leadership as HRBP for 250 employees",
      "Managed employee relations cases and performance improvement processes",
      "Advised managers on Israeli labor law and compliance",
      "Designed compensation bands and benefits programs",
      "Supported a tech company scaling from 80 to 400 people",
    ],
    adjacent: ["Coached leaders on org design and team health", "Handled workplace investigations and terminations"],
    generic: ["Organized company events", "Onboarded new hires", "Maintained HR records"],
    skills: ["HR business partnering", "Employee relations", "HiBob", "Labor law"],
    degrees: ["B.A. Behavioral Sciences, Ruppin", "M.A. Organizational Psychology, Tel Aviv University"],
  },
  {
    key: "fpa",
    count: 3,
    titles: ["Financial Analyst", "FP&A Analyst", "Senior FP&A Manager"],
    core: [
      "Owned the annual budget and quarterly forecasts for a $60M business",
      "Built three-statement financial models in Excel",
      "Delivered monthly variance analysis to the CFO and board",
      "Tracked SaaS metrics: ARR, churn, LTV and CAC",
      "Certified Public Accountant (CPA, Israel)",
    ],
    adjacent: ["Planned headcount and opex with department heads", "Created Google Sheets models for pricing scenarios"],
    generic: ["Prepared financial reports", "Assisted with audits", "Handled accounts payable"],
    skills: ["Excel", "Financial modeling", "NetSuite", "Budgeting"],
    degrees: ["B.A. Accounting & Economics, Tel Aviv University", "B.A. Finance, Bar-Ilan University"],
  },
  {
    key: "writer",
    count: 2,
    titles: ["Content Writer", "Technical Writer", "Senior Technical Writer"],
    core: [
      "Wrote API reference and SDK guides for a payments platform",
      "Maintained docs-as-code in Git and Markdown with PR reviews",
      "Read and tested Python and JavaScript code samples",
      "Generated reference docs from OpenAPI specs",
      "Produced video tutorials for developer onboarding",
    ],
    adjacent: ["Documented REST endpoints for external developers", "Published docs through a static site generator"],
    generic: ["Wrote user manuals", "Edited content for clarity", "Worked with SMEs"],
    skills: ["Markdown", "Git", "OpenAPI", "Docusaurus"],
    degrees: ["B.A. English Literature, Hebrew University", "B.Sc. Computer Science, Open University"],
  },
  {
    key: "se",
    count: 3,
    titles: ["Support Engineer", "Solutions Engineer", "Senior Solutions Engineer"],
    core: [
      "Ran technical product demos for 150+ prospects per year",
      "Wrote Python and JavaScript scripts for customer proof-of-concepts",
      "Integrated customer systems with our REST APIs and webhooks",
      "Pre-sales engineer for a B2B SaaS security platform",
      "Troubleshot customer issues in production with logs and API traces",
    ],
    adjacent: ["Supported account executives in technical evaluations", "Built sample integrations for customer pilots"],
    generic: ["Answered support tickets", "Trained customers on the product", "Wrote knowledge base articles"],
    skills: ["Python", "JavaScript", "REST APIs", "Postman", "SQL"],
    degrees: ["B.Sc. Information Systems, Technion", "B.Sc. Computer Science, Tel Aviv-Yaffo College"],
  },
];
