// 6 screening questions per demo job, derived from each JD by an LLM (Claude) ahead of time
// so the demo runs without an LLM key. source = verbatim JD span. [label, question, req, weight, source, minYears?]

type Q = [string, string, "must" | "nice", number, string, number?];

export const RUBRICS: Record<string, Q[]> = {
  "Senior Full Stack Engineer": [
    ["5+ years professional engineering", "Does the candidate have at least 5 years of professional software engineering experience?", "must", 2, "5+ years of professional software engineering experience", 5],
    ["React in production", "Has the candidate built production front-end applications with React (including React frameworks such as Next.js)?", "must", 3, "Hands-on React development in production applications"],
    ["Node.js backend services", "Has the candidate built backend services running on Node.js (e.g. Express, NestJS)?", "must", 3, "Building backend services with Node.js"],
    ["Relational schema design", "Has the candidate designed or evolved relational database schemas (PostgreSQL or MySQL)?", "must", 2, "Designing relational database schemas (PostgreSQL or MySQL)"],
    ["Cloud production ops", "Has the candidate deployed and operated services on AWS or GCP?", "nice", 1, "Deploying and operating services on AWS or GCP"],
    ["B2B SaaS / tech leadership", "Has the candidate worked on a B2B SaaS product or explicitly led a technical project or mentored engineers?", "nice", 1, "Leading a technical project or mentoring engineers"],
  ],
  "Frontend Engineer": [
    ["3+ years web development", "Does the candidate have at least 3 years of professional web application development?", "must", 2, "3+ years building web applications professionally", 3],
    ["TypeScript", "Does the candidate explicitly write TypeScript (or strongly typed JS with a type checker) professionally?", "must", 3, "Strong TypeScript skills"],
    ["React in production", "Has the candidate shipped production UI built with React?", "must", 3, "Production experience with React"],
    ["Accessibility & responsive UI", "Has the candidate implemented accessible (WCAG, assistive technology) or responsive interfaces?", "must", 2, "Implementing accessible UI (WCAG) and responsive layouts"],
    ["Design systems", "Has the candidate built or maintained a design system or shared component library?", "nice", 1, "Design systems or component libraries"],
    ["Frontend testing", "Has the candidate written automated UI tests with Playwright, Cypress or Testing Library?", "nice", 1, "Testing with Playwright, Cypress or Testing Library"],
  ],
  "Backend Engineer, Payments": [
    ["4+ years backend", "Does the candidate have at least 4 years of backend engineering experience?", "must", 2, "4+ years of backend engineering experience", 4],
    ["Python or Go in production", "Has the candidate built production services in Python or Go?", "must", 3, "Python or Go in production"],
    ["APIs for other teams", "Has the candidate designed REST or gRPC APIs consumed by other teams or services?", "must", 2, "Building REST or gRPC APIs consumed by other teams"],
    ["Payments / billing / ledger", "Has the candidate worked on payments, billing, card processing or ledger systems?", "must", 3, "Payments, billing or ledger systems experience"],
    ["Event-driven systems", "Has the candidate built event-driven systems with Kafka or a similar message broker?", "nice", 1, "Event-driven architectures with Kafka or similar"],
    ["PCI-DSS", "Has the candidate done PCI-DSS compliance work?", "nice", 1, "PCI-DSS compliance work"],
  ],
  "DevOps / Platform Engineer": [
    ["Kubernetes in production", "Has the candidate run Kubernetes clusters or container orchestration in production?", "must", 3, "Running Kubernetes clusters in production"],
    ["Terraform IaC", "Has the candidate written infrastructure as code with Terraform (or an equivalent IaC tool)?", "must", 3, "Infrastructure as code with Terraform"],
    ["AWS operations", "Has the candidate operated production workloads on AWS?", "must", 2, "Operating workloads on AWS"],
    ["CI/CD pipelines", "Has the candidate built CI/CD pipelines?", "must", 2, "Building CI/CD pipelines"],
    ["Observability", "Has the candidate set up monitoring/observability (Prometheus, Grafana, Datadog)?", "nice", 1, "Observability stacks (Prometheus, Grafana, Datadog)"],
    ["Cloud cost optimization", "Has the candidate reduced cloud infrastructure cost?", "nice", 1, "Cost optimization of cloud infrastructure"],
  ],
  "Data Engineer": [
    ["3+ years data engineering", "Does the candidate have at least 3 years of data engineering experience?", "must", 2, "3+ years in data engineering", 3],
    ["Advanced SQL", "Does the candidate write advanced SQL (window functions, CTEs, complex transformations)?", "must", 2, "Advanced SQL"],
    ["Spark or dbt pipelines", "Has the candidate built batch data pipelines with Spark or dbt?", "must", 3, "Building batch pipelines with Spark or dbt"],
    ["Airflow / Dagster orchestration", "Has the candidate orchestrated data workflows with Airflow, Dagster or a similar orchestrator?", "must", 3, "Workflow orchestration with Airflow or Dagster"],
    ["Streaming", "Has the candidate built streaming ingestion with Kafka or Kinesis?", "nice", 1, "Streaming with Kafka or Kinesis"],
    ["Cloud warehouse", "Has the candidate worked with Snowflake, BigQuery or Redshift?", "nice", 1, "Data warehouse experience (Snowflake, BigQuery, Redshift)"],
  ],
  "Machine Learning Engineer": [
    ["Models in production", "Has the candidate trained and deployed machine learning models to production?", "must", 3, "Training and deploying machine learning models to production"],
    ["PyTorch / TensorFlow", "Does the candidate use Python with PyTorch or TensorFlow?", "must", 3, "Python and PyTorch or TensorFlow"],
    ["NLP or recommendations", "Has the candidate worked on NLP or recommendation systems?", "must", 2, "Working with NLP or recommendation systems"],
    ["MLOps", "Has the candidate built MLOps tooling: monitoring, feature stores or experiment tracking?", "nice", 1, "MLOps: model monitoring, feature stores, experiment tracking"],
    ["LLM fine-tuning/evaluation", "Has the candidate fine-tuned or evaluated large language models?", "nice", 1, "Large language model fine-tuning or evaluation"],
    ["Research / open source", "Has the candidate published ML research or maintained open-source ML work?", "nice", 1, "Published research or open-source ML work"],
  ],
  "iOS Engineer": [
    ["3+ years native iOS", "Does the candidate have at least 3 years of native iOS development?", "must", 2, "3+ years of native iOS development", 3],
    ["Swift + SwiftUI/UIKit", "Does the candidate build iOS apps in Swift with SwiftUI or UIKit?", "must", 3, "Swift and SwiftUI or UIKit"],
    ["App Store releases", "Has the candidate shipped apps to the App Store?", "must", 3, "Shipping apps to the App Store"],
    ["Offline-first sync", "Has the candidate implemented offline-first data sync on mobile?", "nice", 1, "Offline-first data sync"],
    ["Mobile CI", "Has the candidate automated mobile builds with Fastlane or Xcode Cloud?", "nice", 1, "Mobile CI (Fastlane, Xcode Cloud)"],
    ["Cross-platform", "Has the candidate worked with React Native or Flutter?", "nice", 1, "Experience with React Native or Flutter"],
  ],
  "QA Automation Engineer": [
    ["E2E test automation", "Has the candidate written automated end-to-end tests with Playwright, Cypress or Selenium?", "must", 3, "Writing automated end-to-end tests (Playwright, Cypress or Selenium)"],
    ["API testing & frameworks", "Has the candidate automated API tests or built test automation frameworks?", "must", 3, "API testing and test automation frameworks"],
    ["Tests in CI", "Has the candidate integrated automated tests into CI pipelines?", "must", 2, "Integrating tests into CI pipelines"],
    ["Performance testing", "Has the candidate run performance or load tests?", "nice", 1, "Performance or load testing"],
    ["TypeScript or Python", "Does the candidate program in TypeScript or Python?", "nice", 1, "Programming experience in TypeScript or Python"],
    ["Owning automation", "Has the candidate owned test automation for web and API products end to end?", "nice", 1, "Own test automation for our web and API products"],
  ],
  "Application Security Engineer": [
    ["Threat modeling & code review", "Has the candidate done threat modeling or secure code review?", "must", 3, "Application security experience: threat modeling and secure code review"],
    ["Pentests / bug bounty", "Has the candidate run penetration tests or a bug bounty program?", "must", 3, "Running penetration tests or bug bounty programs"],
    ["Cloud security", "Has the candidate secured cloud environments (AWS, GCP or Azure)?", "must", 2, "Securing cloud environments (AWS, GCP or Azure)"],
    ["SAST/DAST in CI", "Has the candidate integrated SAST/DAST tooling into CI?", "nice", 1, "SAST/DAST tooling in CI"],
    ["Certifications", "Does the candidate hold a security certification such as OSCP or CISSP?", "nice", 1, "Security certifications (OSCP, CISSP)"],
    ["SOC 2 / ISO 27001", "Has the candidate driven a compliance program such as SOC 2 or ISO 27001?", "nice", 1, "Compliance programs such as SOC 2 or ISO 27001"],
  ],
  "Engineering Manager": [
    ["People management", "Has the candidate managed software engineers, including hiring, 1:1s and performance?", "must", 3, "Managing a team of software engineers (hiring, 1:1s, performance)"],
    ["Hands-on engineering past", "Does the candidate have a documented hands-on software engineering background?", "must", 3, "Hands-on software engineering background"],
    ["Cross-team delivery", "Has the candidate delivered projects spanning multiple teams?", "must", 2, "Delivering projects across multiple teams"],
    ["Scaling a team", "Has the candidate grown or scaled a team through rapid growth?", "nice", 1, "Scaling a team through rapid growth"],
    ["SaaS company", "Has the candidate worked at a SaaS company?", "nice", 1, "Experience in a SaaS company"],
    ["Team size 6–8", "Has the candidate led a team of roughly 6 or more engineers?", "nice", 1, "Lead a team of 6–8 engineers building our core product."],
  ],
  "Product Manager, B2B SaaS": [
    ["3+ years product management", "Does the candidate have at least 3 years of product management experience?", "must", 2, "3+ years of product management experience", 3],
    ["B2B SaaS product", "Has the candidate managed a B2B SaaS product?", "must", 3, "Managing a B2B SaaS product"],
    ["Enterprise customer discovery", "Has the candidate worked directly with enterprise customers on discovery?", "must", 3, "Working directly with enterprise customers on discovery"],
    ["Product metrics", "Has the candidate defined and tracked product metrics?", "must", 2, "Defining and tracking product metrics"],
    ["Technical background", "Does the candidate have a technical background or engineering degree?", "nice", 1, "Technical background or engineering degree"],
    ["Pricing & packaging", "Has the candidate worked on pricing or packaging?", "nice", 1, "Experience with pricing or packaging"],
  ],
  "Product Designer": [
    ["End-to-end product design", "Has the candidate designed end-to-end product flows for web or mobile apps?", "must", 3, "End-to-end product design for web or mobile apps"],
    ["Figma & prototyping", "Does the candidate use Figma and build prototypes?", "must", 2, "Figma proficiency and prototyping"],
    ["User research", "Has the candidate conducted user research or usability testing?", "must", 3, "Conducting user research and usability testing"],
    ["Shipped portfolio", "Does the candidate reference shipped work or a portfolio?", "must", 2, "A portfolio of shipped work"],
    ["Design system", "Has the candidate built or maintained a design system?", "nice", 1, "Building or maintaining a design system"],
    ["Data-heavy dashboards", "Has the candidate designed data-heavy dashboards?", "nice", 1, "Designing data-heavy dashboards"],
  ],
  "Data Analyst": [
    ["SQL at scale", "Does the candidate use SQL for analysis on large datasets?", "must", 3, "SQL for analysis on large datasets"],
    ["BI dashboards", "Has the candidate built dashboards in Looker, Tableau or Power BI?", "must", 3, "Building dashboards in Looker, Tableau or Power BI"],
    ["Stakeholder insights", "Has the candidate presented insights to business stakeholders?", "must", 2, "Presenting insights to business stakeholders"],
    ["Python or R", "Does the candidate use Python or R for analysis?", "nice", 1, "Python or R for analysis"],
    ["A/B testing", "Has the candidate designed or analyzed A/B tests?", "nice", 1, "A/B test design and analysis"],
    ["Business analysis", "Has the candidate answered business questions from warehouse data independently?", "nice", 1, "SQL for analysis on large datasets"],
  ],
  "Customer Success Manager": [
    ["B2B SaaS portfolio", "Has the candidate managed a portfolio of B2B SaaS customers?", "must", 3, "Managing a portfolio of B2B SaaS customers"],
    ["Renewals & expansion", "Has the candidate driven renewals and expansion revenue?", "must", 3, "Driving renewals and expansion revenue"],
    ["Onboarding & QBRs", "Has the candidate run customer onboarding or business reviews (QBRs)?", "must", 2, "Running onboarding and business reviews (QBRs)"],
    ["Enterprise accounts", "Has the candidate managed enterprise accounts?", "nice", 1, "Enterprise accounts experience"],
    ["CS platforms", "Has the candidate used Gainsight or a similar customer success platform?", "nice", 1, "Experience with Gainsight or similar CS platforms"],
    ["Retention metrics", "Does the candidate report retention or NRR outcomes?", "nice", 1, "Driving renewals and expansion revenue"],
  ],
  "Account Executive, Mid-Market": [
    ["2+ years closing SaaS", "Does the candidate have at least 2 years of closing B2B SaaS deals?", "must", 2, "2+ years of closing B2B SaaS deals", 2],
    ["Quota attainment", "Has the candidate consistently met or exceeded a sales quota?", "must", 3, "Consistently meeting or exceeding a sales quota"],
    ["Full-cycle sales", "Has the candidate run full-cycle sales from discovery to close?", "must", 3, "Running full-cycle sales from discovery to close"],
    ["Technical buyers", "Has the candidate sold to technical buyers (CTOs, engineering, IT)?", "nice", 1, "Selling to technical buyers"],
    ["Salesforce", "Has the candidate used Salesforce CRM?", "nice", 1, "Salesforce CRM experience"],
    ["New logos", "Has the candidate closed new-logo SaaS business?", "nice", 1, "2+ years of closing B2B SaaS deals"],
  ],
  "Growth Marketing Manager": [
    ["Paid acquisition", "Has the candidate run paid acquisition campaigns on Google Ads, Meta or LinkedIn?", "must", 3, "Running paid acquisition campaigns (Google Ads, Meta, LinkedIn)"],
    ["Budget & CAC", "Has the candidate owned a marketing budget and CAC targets?", "must", 3, "Owning a marketing budget and CAC targets"],
    ["Funnel experimentation", "Has the candidate run landing page or funnel experiments?", "must", 2, "Experimentation on landing pages and funnels"],
    ["Marketing automation", "Has the candidate used HubSpot or Marketo marketing automation?", "nice", 1, "Marketing automation (HubSpot, Marketo)"],
    ["B2B SaaS marketing", "Has the candidate marketed a B2B SaaS product?", "nice", 1, "B2B SaaS marketing experience"],
    ["Channel breadth", "Has the candidate managed spend across more than one paid channel?", "nice", 1, "Running paid acquisition campaigns (Google Ads, Meta, LinkedIn)"],
  ],
  "HR Business Partner": [
    ["HRBP with leadership", "Has the candidate been an HR business partner to leadership teams?", "must", 3, "HR business partnering with leadership teams"],
    ["Employee relations & performance", "Has the candidate handled employee relations and performance management processes?", "must", 3, "Employee relations and performance management processes"],
    ["Labor law", "Has the candidate advised on labor law or employment compliance?", "must", 2, "Knowledge of labor law"],
    ["Tech company growth", "Has the candidate supported a tech company through growth?", "nice", 1, "Supporting a tech company through growth"],
    ["Comp & benefits", "Has the candidate designed compensation or benefits programs?", "nice", 1, "Compensation and benefits programs"],
    ["Org scale", "Has the candidate supported an organization of 100+ employees?", "nice", 1, "HR business partnering with leadership teams"],
  ],
  "FP&A Analyst": [
    ["Planning & forecasting", "Has the candidate done financial planning, budgeting and forecasting?", "must", 3, "Financial planning, budgeting and forecasting"],
    ["Financial modeling", "Has the candidate built financial models in Excel or Google Sheets?", "must", 3, "Advanced Excel or Google Sheets financial modeling"],
    ["Variance reporting", "Has the candidate delivered monthly variance analysis to management?", "must", 2, "Monthly variance analysis and reporting to management"],
    ["SaaS metrics", "Has the candidate tracked SaaS metrics such as ARR, churn or LTV?", "nice", 1, "SaaS metrics (ARR, churn, LTV)"],
    ["CPA / finance degree", "Does the candidate hold a CPA or a finance degree?", "nice", 1, "CPA or finance degree"],
    ["Board / CFO reporting", "Has the candidate reported to a CFO or board?", "nice", 1, "Monthly variance analysis and reporting to management"],
  ],
  "Technical Writer": [
    ["Developer docs", "Has the candidate written developer documentation for APIs or SDKs?", "must", 3, "Writing developer documentation for APIs or SDKs"],
    ["Reads code", "Does the candidate read or test code samples in a programming language?", "must", 3, "Reading code samples in at least one programming language"],
    ["Docs-as-code", "Has the candidate worked in docs-as-code workflows (Git, Markdown)?", "must", 2, "Docs-as-code workflows (Git, Markdown)"],
    ["OpenAPI / docs platforms", "Has the candidate used OpenAPI or a docs platform?", "nice", 1, "Experience with OpenAPI or docs platforms"],
    ["Tutorials & video", "Has the candidate created tutorials or video content?", "nice", 1, "Creating tutorials or video content"],
    ["External developer audience", "Has the candidate documented products for external developers?", "nice", 1, "Writing developer documentation for APIs or SDKs"],
  ],
  "Solutions Engineer": [
    ["Technical demos", "Has the candidate run technical product demos for prospects?", "must", 3, "Running technical product demos for prospects"],
    ["Scripting / coding", "Can the candidate script or code in Python or JavaScript?", "must", 3, "Scripting or coding ability (Python, JavaScript)"],
    ["API integration POCs", "Has the candidate integrated APIs for customer proof-of-concepts?", "must", 2, "Integrating APIs for customer proof-of-concepts"],
    ["B2B SaaS pre-sales", "Has the candidate worked in pre-sales for a B2B SaaS product?", "nice", 1, "Pre-sales in B2B SaaS"],
    ["Customer troubleshooting", "Has the candidate troubleshot customer-facing technical issues?", "nice", 1, "Customer-facing troubleshooting experience"],
    ["Supporting sales", "Has the candidate supported account executives in technical evaluations?", "nice", 1, "Running technical product demos for prospects"],
  ],
};
